package br.com.marketimobi.api.model.enums;

public enum TipoTextoSistema {
	
	FIXO_INFORMADO,
	
	IMOBILIARIA_NOME,
	IMOBILIARIA_RAZAO_SOCIAL,
	IMOBILIARIA_TELEFONE_FIXO,
	IMOBILIARIA_TELEFONE_CELULAR,
	IMOBILIARIA_LOGRADOURO,
	IMOBILIARIA_COMPLEMENTO,
	IMOBILIARIA_BAIRRO,
	IMOBILIARIA_CEP,
	IMOBILIARIA_CIDADE,
	IMOBILIARIA_ESTADO,
	IMOBILIARIA_EMAIL,
	IMOBILIARIA_SITE,
	IMOBILIARIA_CRECI,
	IMOBILIARIA_CNPJ,
	
	USUARIO_NOME,
	USUARIO_SOBRENOME,
	USUARIO_NOME_PROFISSIONAL,
	USUARIO_TELEFONE_FIXO,
	USUARIO_TELEFONE_CELULAR,
	USUARIO_CARGO,
	USUARIO_CRECI,
	USUARIO_EMAIL,
	USUARIO_SITE;

}
