CREATE TABLE produto (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	codigo VARCHAR(10) NOT NULL,
	nome VARCHAR(30) NOT NULL,
	descricao VARCHAR(50) NOT NULL,
	data_cadastro DATE NOT NULL,
	id_categoria BIGINT(20) NOT NULL,
	gerar_png BOOLEAN NOT NULL,
	gerar_pdf BOOLEAN NOT NULL,
	imagem VARCHAR(250) NOT NULL,
	largura_imagem SMALLINT NOT NULL,
	altura_imagem SMALLINT NOT NULL,
	imagem_card VARCHAR(250) NOT NULL,
	largura_imagem_card SMALLINT NOT NULL,
	altura_imagem_card SMALLINT NOT NULL,
	largura_imagem_amostra SMALLINT NOT NULL,
	altura_imagem_amostra SMALLINT NOT NULL,
	imagem_fundo VARCHAR(250) NOT NULL,
	principal BOOLEAN NOT NULL,
	CONSTRAINT uk_produto_codigo UNIQUE (codigo),
	CONSTRAINT uk_produto_nome UNIQUE (nome),
	FOREIGN KEY (id_categoria) REFERENCES categoria(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE item_produto (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	id_produto BIGINT(20) NOT NULL,
	descricao VARCHAR(50) NOT NULL,
	sequencia SMALLINT NOT NULL,
	etiqueta VARCHAR(30),
	orientacao_usuario VARCHAR(30),
	tipo VARCHAR(30) NOT NULL,
	origem VARCHAR(30) NOT NULL,
	largura SMALLINT NOT NULL,
	altura SMALLINT NOT NULL,
	posicao_x SMALLINT NOT NULL,
	posicao_y SMALLINT NOT NULL,
	tipo_imagem_sistema VARCHAR(30),
	imagem_sistema VARCHAR(250),
	tipo_texto_sistema VARCHAR(30),
	texto_sistema VARCHAR(100),
	qtd_max_caracteres SMALLINT,
	fonte VARCHAR(30),
	tamanho_fonte SMALLINT,
	cor_fonte_r SMALLINT,
	cor_fonte_g SMALLINT,
	cor_fonte_b SMALLINT,
	tipo_fonte VARCHAR(30),
	alinhamento_texto VARCHAR(30),
	FOREIGN KEY (id_produto) REFERENCES produto(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;